import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import { Providers } from '@/providers/provider'
import Footer from '@/components/footer'



const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Badaro Eventos',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <body className={`${inter.className} bg-[#f1f1f1dd] h-screen flex flex-col`}>
        <Providers>
          <Header />
          <div className="flex-grow">
            {/* Conteúdo da página (children) aqui */}
            {children}
          </div>




          <Footer />



        </Providers>
      </body>
    </html>
  )
}
